### DISCUSSION TITLE
How to include catalogs with assets containing multiple variables as a nested catalog

### DISCUSSION THREAD

**Discussion by dougiesquire** [intake/intake-esm#583] [General]
I'd like to set up a catalog of intake-esm catalogs, e.g. a `catalog.yaml` file something like: 

```yaml
plugins:
  source:
  - module: intake_xarray
  - module: intake_esm

sources:
  esm_catalog_0:
    args:
      obj: /path/to/esm_catalog_0.json
    driver: intake_esm.esm_datastore
    metadata: {}
  esm_catalog_1:
    args:
      obj: /path/to/esm_catalog_1.json
    driver: intake_esm.esm_datastore
    metadata: {}
```

However, my intake-esm catalogs have assets containing multiple variables. This [require passing a _function_](https://intake-esm.readthedocs.io/en/latest/how-to/use-catalogs-with-assets-containing-multiple-variables.html#use-catalogs-with-assets-containing-multiple-variables) as an argument which I can't do with my `catalog.yaml`.

Is it possible to set up a catalog of nested intake-esm catalogs with multi-variable assets that works by default? I'm aware I can pass the `read_csv_kwargs` when querying the catalog as follows, but it would be nicer if this could be configured in `catalog.yaml`:

```python
cat = intake.open_catalog("catalog.yaml")
esm_catalog_0 = cat.esm_catalog_0(
    read_csv_kwargs={"converters": {"variable": ast.literal_eval}}
)
```

If this is not possible, is there interested in making it possible (e.g., by adding a boolean parameter `multi_variable_assets` to the `intake_esm.core.esm_datastore` API)?
