### ISSUE TITLE
catalogue that used to work with previous version is now failing when loading entry

### ISSUE THREAD

**Issue by paolap** [intake/intake-esm#535]
Hi, 

we have two catalogues that work fine with the odder version of intake-esm but that failed to load a entry once we upgraded to the new version. 
I've initially posted this issue on the intake repository, as we updated to 0.6.6 at the same time and the error seems to be in the intake code when an entry is loaded.
Many more details, included a test catalogue are in 

https://github.com/intake/intake/issues/686

I'm just posting here the error and the show_versions output as requested.

>>> intake_esm.show_versions()

INSTALLED VERSIONS
------------------

cftime: 1.6.2
dask: 2022.9.1
fastprogress: 1.0.3
fsspec: 2022.8.2
gcsfs: None
intake: 0.6.6
intake_esm: 2022.9.18
netCDF4: 1.6.1
pandas: 1.5.0
requests: 2.28.1
s3fs: None
xarray: 2022.6.0
zarr: 2.12.0
>>> cat = intake.open_catalog('/g/data/ua8/Working/packages/intake-test/catalogue.yaml')
>>> era5 = cat.era5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/data/ua8/Working/packages/notworking/lib/python3.9/site-packages/intake/catalog/base.py", line 391, in __getattr__
    return self[item]  # triggers reload_on_change
  File "/g/data/ua8/Working/packages/notworking/lib/python3.9/site-packages/intake/catalog/base.py", line 436, in __getitem__
    s = self._get_entry(key)
  File "/g/data/ua8/Working/packages/notworking/lib/python3.9/site-packages/intake/catalog/utils.py", line 45, in wrapper
    return f(self, *args, **kwargs)
  File "/g/data/ua8/Working/packages/notworking/lib/python3.9/site-packages/intake/catalog/base.py", line 323, in _get_entry
    return entry()
  File "/g/data/ua8/Working/packages/notworking/lib/python3.9/site-packages/intake/catalog/entry.py", line 77, in __call__
    s = self.get(**kwargs)
  File "/g/data/ua8/Working/packages/notworking/lib/python3.9/site-packages/intake/catalog/local.py", line 290, in get
    data_source = plugin(**open_args)
TypeError: __init__() got an unexpected keyword argument 'metadata'

Many thanks, Paola

**Comment by andersy005** [comment]
thank you for reporting this, @paolap! This is certainly a bug, and i just open a PR with a fix. 

By the way, with the new version of `intake-esm`, you will need to update the `esmcol_obj` to `obj` in your `catalogue.yaml` 

```yaml
metadata:
    version: 1
sources:
    era5:
        description: |
            ECMWF ERA5 Reanalysis
            Requires access to /g/data/rt52
            Files managed by NCI, contact help@nci.org.au
            https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation
            https://opus.nci.org.au/display/ERA5/ERA5+Community+Home
        driver: intake_esm.esm_datastore
        args:
            obj: '{{CATALOG_DIR}}/era5/catalogue.json'
```
