### ISSUE TITLE
Improve functionality for assets with Attributes containing iterables

### ISSUE THREAD

**Issue by dougiesquire** [intake/intake-esm#587]
**Is your feature request related to a problem? Please describe.**
It’s pretty common to have intake-esm assets that have multiple variables. The [current approach](https://intake-esm.readthedocs.io/en/stable/how-to/use-catalogs-with-assets-containing-multiple-variables.html) for dealing with these assets is to save an iterable of variables in the `variable_column` and pass a converter function to `intake_esm.esm_datastore`.

It’s also common to provide standard intake yaml descriptions of intake-esm catalogs (e.g. see [here](https://github.com/pangeo-data/pangeo-datastore/blob/master/intake-catalogs/climate.yaml)) to be passed to `intake.open_catalog`. The `args` to be passed to the `intake_esm.esm_datastore` driver are specified within the yaml file. It’s not possible to specify Python functions, meaning that assets with multiple variables can’t work by default.

**Describe the solution you'd like**
Is it possible to fix this, so that an intake yaml description of an intake-esm catalog with multi-variable assets can work by default? E.g., a simple fix would be to add an optional `columns_with_iterables` parameter to the `intake_esm.esm_datastore` API that specifies the columns to convert with `ast.literal_eval`. Then, for example,

```yaml
sources:
  data0:
    args:
      obj: "/path/to/esm_cat.json"
      columns_with_iterables:
        - "variable"
        - "another"
    description: ""
    driver: intake_esm.esm_datastore
    metadata: {}
```
should provide a functional esm catalog when passed to `intake.open_catalog`.

**Describe alternatives you've considered**
I'm aware that users can use [`.configure_new`](https://intake.readthedocs.io/en/latest/catalog.html#local-catalogs) to override/add arguments for a source, but in this context this requires users to know which columns need converting which is not necessarily the case.
