### ISSUE TITLE
intake-esm called from intake break depending of intake-esm versions 

### ISSUE THREAD

**Issue by ltroussellier** [intake/intake-esm#597]
I got a "masterCat.yml" witch is a classic intake catalog. This catalog sources are differents intake-esm catalog : 

```

description: 'master catalog for all data pool catalogs available'

plugins:
  source:
    - module: intake_esm

sources:
  
  CORDEX:
    args:
       esmcol_obj: CORDEX.json
    description: 'CORDEX data pool '
    driver:
    - intake.open_esm_datastore

.... other sources 
```

the cordex.json is a classic esm-catalog 

---

when python call the esm catalog from the yml catalog : there are issues depending on the version of intake-esm. 
```
import intake
catMaster = intake.open_catalog("master.yml")
print(catMaster["CORDEX"])
```

From my tests,  the version of intake lib does not change anything for the code above. So lets assume intkae version == 0.6.8 (the last one, and the available on pip package) 

Then intake-esm 
version == 2021.1.15 => No problem
version == 2021.8.17 => No problem
version == 2022.9.18 => PROBLEM => TypeError: esm_datastore.__init__() got an unexpected keyword argument 'metadata'
version == from github sources => TypeError: esm_datastore.__init__() missing 1 required positional argument: 'obj'

from github sources,  i can get around my loading problem by modifying **esmcol_obj: CORDEX.json** into **obj: CORDEX.json** then everythings is OK 

To get my catalogs working as expected, i cant use the git sources versions. So I have 2 solutions 
1/ install the previous version ("2021.8.17") on the python environment
2/ wait for the update of the pip package  

is it possible to update the pip package with latest sources ? that way, i only have to modify the yml and everything get back to normal ? 

LT
